noteable-io/noteable-notebook-magics

CHANGELOG.md
noteable_magics/ntbl.py
noteable_magics/planar_ally_client/api.py
tests/planar_ally_client/test_api.py
tests/test_ntbl.py

Adds new feature `%ntbl change-log-level --rtu-level DEBUG` to enable debug logs for RTU-specific library/code sections (as defined in PA code)
Makes `--app-level` optional in `change-log-level` command. If it's omitted, then PA `planar_ally.*` logs will revert to default PA level (INFO).
Loom video of feature in action: https://www.loom.com/share/cfa6e9c6800b4d0095c1d8fd8d1e8830
PA PR that needs to get merged before this goes online: https://github.com/noteable-io/planar-ally/pull/235

RTU log level in PA

---

CHANGELOG.md
noteable_magics/__init__.py
noteable_magics/data_loader.py
noteable_magics/sql/connection.py
noteable_magics/sql/magic.py
poetry.lock
pyproject.toml
tests/test_data_loader.py
tests/test_datasources.py

The following code now works in ipython sessions in the polymorph image when using this branch
```
In [3]: import pandas as pd
In [4]: data = {
...:   "calories": [420, 380, 390],
...:   "duration": [50, 40, 45]
...: }
In [5]: df = pd.DataFrame(data)
In [6]: %sql @noteable df2 << select * from df limit 2
Returning data to local variable df2
In [7]: df2
Out[7]: 
calories  duration
0       420        50
1       380        40
```
- `@noteable` database connection uses sqlite to perform local SQL operations
- `@noteable` database connection now uses duckdb by default via the duckdb sql-alchemy library

Changed default @noteable data connector to use duckdb

---

CHANGELOG.md
noteable_magics/sql/magic.py
noteable_magics/sql/run.py
poetry.lock
pyproject.toml
tests/test_sql_magic.py

- Install and use [jinjasql](https://github.com/sripathikrishnan/jinjasql) to preprocess SQL cell query contents, per ENG-4797 and using what our peers deepnote and hex use.
- Only not-sql-injection-safe string Template interpolation inherited from sql-magic.
- Removal of not-sql-injection-safe string Template interpolation inherited from sql-magic.
- Use jinjasql for any possible template expansion of the SQL query.
- Tests in `tests/test_sql_magic.py::TestSqlMagic` show that non-templated queries continue to work, while `...::TestJinjaTemplatesWithinSqlMagic` tests various jinjasql-features.

Eng 4797 Install jinjasql, use it to maybe expand SQL cell contents.

---

CHANGELOG.md
noteable_magics/sql/connection.py
noteable_magics/sql/magic.py
tests/test_sql_magic.py

... is attempted to be used.
- If an unknown datasource is attempted to be used (say, `%sql @45656745 select true`, when  `@45656745` was not present at bootstrapping time most likely because the datasource was created after when the kernel was launched, print as cell's output "Cannot find data connection. If you recently created this connection, please restart the kernel." per ENG-4264.
- Get a really unhelpful message, printed twice, sandwitching an underlying SQLA exception when trying to create a new Engine with way not enough info:
`Connection info needed in SQLAlchemy format, example: postgresql://username:password@hostname/dbname or an existing connection: dict_keys(['@0b2c5a31da854e49ad534a55a7788925', '@noteable']) …

Simpler, more end-user oriented message if an unknown datasource... 

---

noteable_magics/sql/meta_commands.py
noteable_magics/sql/run.py
tests/test_sql_magic_meta_commands.py

- Implement `\list` , `\tables` , `\views` (and aliases `\dr`, `\dt`, `\dv`) within SQL cells. See ENG-4996 for full specification of behavior.

Implement meta commands \tables, \views, \list to return table/view/whatever names in schema(s).

---

noteable_magics/sql/meta_commands.py
tests/test_sql_magic_meta_commands.py

Presentation tweaks for currently implemented functionality.
Given feedback on https://app.noteable-integration.us/f/87245cba-be66-4e76-baab-f200fdf143cb/Scratch.ipynb :
- Reorder columns and rows of \help to try to get the most important things first.
- One row per schema + relation from \list variants instead of one row per schema only, then with the relation names comma joined slammed into single dataframe cell.
- When running \list / \dr , inject additional column clarifying if relation is a table or a view.
- Add a \<br /> at the start of a view definition HTML block to space it out a bit from the bottom of the structure table. Is too tight right now.

Tweak SQL cell meta commands / outputs

---

noteable_magics/sql/meta_commands.py
tests/conftest.py
tests/test_sql_magic_meta_commands.py

- Show a second datagframe describing the indices defined on a table when a table is `\describe`'d

Show information about indices defined on a table when doing \describe <table>

---

noteable_magics/sql/meta_commands.py
poetry.lock
tests/test_sql_magic_meta_commands.py
tox.ini

- Presentation tweaks for the 'U' release discussed with @noteabledave :
- DEX is not set up for single cells `display()`ing _multiple_ dataframes -- the display control metadata in the cell (like, say, 'title') is applied to all dataframes displayed by the cell. So, when describing indices of a table, err on the side of a hand-formatted HTML block instead of directly display()ing the dataframe. That way we can give it a distinguishing title so the user knows what they're seeing.
- Emit table / view names in the HTML \<h2> title blocks within \<code> tags instead of either single or double quotes.

Presentation tweaks.

---

noteable_magics/sql/meta_commands.py
tests/test_sql_magic_meta_commands.py

- Have `\help` render its dataframe down to a HTML table and call `display()` directly with it, because DEX currently doesn't work well with these strings for a human-readable documentation purpose.
- Standardize punctuation in help contents.
- `\help` datagframe displayed poorly by DEX currently.
- `\help` contents phrasing is inconsistent.
- `\help` renders its dataframe down to a HTML table and call `display()` directly with it.
- Standardize punctuation in help messages.
Have the single-command help text also include an example blurb showing usage examples. Ran out of time this sprint.

Datasource help display manual HTML table

---

noteable_magics/sql/meta_commands.py
tests/test_sql_magic_meta_commands.py

- Stop being tricked by Inspector.get_pk_index() returning a nonempty dict but having no 'constrained_columns' members. That seems to be how it [undocumentedly](https://docs.sqlalchemy.org/en/14/core/reflection.html#sqlalchemy.engine.reflection.Inspector.get_pk_constraint) indicates 'there is no primary key here at all'.
- Switch the attrs structure to match what [dex and dx should start to honor](https://noteable-io.github.io/dx/plotting/overview/#using-pandas-dataframe-attrs) and title some of the returned dataframes.
- I'm aiming to include this in Vail.
- We think there are primary key constraints / indexes when really there aren't
- We don't describe dataframe attr titles in path that dex / dx will pick up and honor.
- Stop …

Better primary key index handling; try to get dataframes titled

---

noteable_magics/sql/run.py
tests/conftest.py
tests/test_sql_magic.py

- Fix DDL commands like 'CREATE TABLE,' etc. Got broken somewhere within most recent [PR-62](https://github.com/noteable-io/noteable-notebook-magics/pull/62), on staging but not in production yet because there were no automated tests over DDL. Now gots 'em.
- While here, make it so that the assigned cell result coming from statements that only return a rowcount, like 'DELETE from foo where id in (1, 5, 7, 9)' will be that affected rowcount -- say, an integer 4 in this case.
- Also test that we behave more like a SQL client in face of a SELECT statement that matches no rows, which is to produce _a properly column'd but zero-length dataframe_. **This portion may or may not be controversial**. We might actually like / prefer the …

Eng 5268 fix sql cell create table

---

noteable_magics/sql/meta_commands.py
tests/conftest.py
tests/test_sql_magic.py
tests/test_sql_magic_meta_commands.py

- The SQLAlchemy-side type descriptor object returned when introspecting into a PG-ish uuid column does not implement the `as_generic()` method all of the prior encountered data types do. So catch an exception, and stringify it a different way.
- While here and needing to have the test suite create a table in CRDB just for this one test, adjust the fixtures so that any newly created tables within a test will be automatically dropped.
- Cannot `\describe` a table that has a UUID column. Like, oh, any from reproductions of our gate database.
- Tests in this test suite must be sure to clean up their own newly created tables otherwise will break some of the downstream introspection tests.
- Can now introspect into …

Fix \describe vs tables with PGish uuid columns, ENG-5254.

---

noteable_magics/datasource_postprocessing.py
poetry.lock
pyproject.toml
tests/test_datasources.py
tests/test_sql_magic.py

- Add in support and tests for datasource type AWS Athena and how Gate will be presenting the data in the JSONs.
- See https://app.noteable-integration.us/f/bc4e9990-6593-4411-992a-b61a88676cae for the baseline exploration that inspired this.
- Driver homepage at https://github.com/laughingman7743/PyAthena/
- The main new test proving end-end functionality, TestAmazonAthena, needs credentials in environment variables, else it will politely skip itself. If you want to run locally, ask James. He's done it.

Magics support for AWS Athena

---

noteable_magics/sql/meta_commands.py
tests/conftest.py
tests/test_sql_magic_meta_commands.py

- Teach SQL Cell `\describe <table_name>` to dig up information about the outbound foreign keys constraining columns in <table_name>. Handles compound (multi-column) foreign keys. Will display the results as a HTML table similar to how indexes are displayed.
Single simple FK:
----
<h2>Table <code>references_int_table</code> Foreign Keys</h2>
<br />
<table border="1" class="dataframe">
<thead>
<tr style="text-align: right;">
<th>Foreign Key</th>
<th>Columns</th>
<th>Referenced Table</th>
<th>Referenced Columns</th>
</tr>
</thead>
<tbody>
<tr>
<td>references_int_table_a_id_fkey</td>
<td>a_id</td>
<td>int_table</td>
<td>a</td>
</tr>
</tbody>
</table>
Single compound FK:
----
<h2>Table <code>references_int_table_2</code> Foreign …

Describe outbound foreign keys in SQL Cell \describe output.

---

noteable_magics/sql/meta_commands.py
tests/conftest.py
tests/test_sql_magic.py
tests/test_sql_magic_meta_commands.py

- Display check constraints defined on a table when `\describe`ing it. Sample:
<h2>Table <code>str_table</code> Check Constraints</h2>
<br />
<table border="1" class="dataframe">
<thead>
<tr style="text-align: right;">
<th>Constraint</th>
<th>Definition</th>
</tr>
</thead>
<tbody>
<tr>
<td>never_f_10</td>
<td>NOT ((str_id = 'f'::STRING) AND (int_col = 10))</td>
</tr>
<tr>
<td>only_even_int_col_values</td>
<td>(int_col % 2) = 0</td>
</tr>
<tr>
<td>single_char_str_id</td>
<td>length(str_id) = 1</td>
</tr>
</tbody>
</table>

Eng 5335 sql cell describe to enumerate constraints

---

noteable_magics/sql/meta_commands.py
tests/test_sql_magic_meta_commands.py

- Simplify the \<h2> title contents of the secondary dataframes-as-html being displayed by SQL cell metadata commands like \describe and so on. The main dataframe displayed by dex (the table / view structure) will be titled something like 'Table `\<tablename>` Definition', setting a clear enough stage so that the subsequent cell outputs can just be titled 'Indexes', 'Foreign Keys', 'Check Constraints' instead of repeating 'Table <table_name>' over and over. Now that we include describing foreign keys and check constraints the repetition was heavy handed. 
- Repeatedly say 'Table <table_name>' in the \<h2> elements titling the next set of metadata for the table. The repetition is unnecessary.
- Just say 'Indexes', 'Foreign Keys', …

Simplify titles of secondary metadata HTML tables.

---

noteable_magics/sql/gate_messaging_types.py
noteable_magics/sql/meta_commands.py
tests/conftest.py
tests/test_sql_magic.py
tests/test_sql_magic_meta_commands.py

New (undocumented) meta command \introspect to drive whole-database introspection and POSTing each discovered relation's structure up into Gate. Will ultimately be driven either magically at datasource creation time, or at worst through datasource '...' GUI element.
Was prototyped using a notebook calling into the existing Gate POST endpoint, over at [this notebook on integration](https://app.noteable-integration.us/f/94bc54fd-4cf8-47c0-a82c-8195753735ad/ThreadPoolExecutor.ipynb).
Open questions for future work:
* Default concurrency level? Introspecting via the only API available in SQLA 1.4 requires many round-trips per relation, so is inherently slow. Can speed up over all using the ThreadPoolExecutor as we are here, but at what concurrency? Don't want to surpass the remote db's max …

Drive full introspsection and reporting back to gate via SQL cell \introspect

---

noteable_magics/sql/meta_commands.py
tests/test_sql_magic_meta_commands.py

Make call into [new as of yesterday gate route](https://github.com/noteable-io/gate/pull/2513) to delete any prior introspection records for this datasource _older_ than when we started this full introspection pass.
This fixes garbage leak in following scenario:
* Tables A, B get created in datasource database.
* Introspection _Alpha_ happens, Gate informed of both A, B.
* Table B gets _dropped_ from database.
* Introspection _Beta_ happens, informing Gate of perhaps updated structure for A _only_. The Gate-side row describing A will have an new created_at value (will be whole new row). The now-lying garbage row for B will still have created_at timestamp from _Alpha_ pass.
Table B's description would linger in gate database.
Now, with this PR, the second introspection, upon successful …

Fire off DELETE request to purge any stale introspection records after successful introspection pass.

---

poetry.lock
pyproject.toml

- Add pymysql (pure python mysql db driver) to support talking to mysql/mariadb/singlestore databases through SQL cells. pymysql chosen over mysqlclient, in that mysqlclient requires mysql/mariadb client C libraries already installed and lacks an equivalent to psycopg2-binary package.
- Run `poetry update` to get fresher versions of all sorts of packages, but specifically 'future 0.18.2 -> 0.18.3' to squelch a new safety complaint.
Tested pymysql -> singlestore already on integration through ad-hoc means against singlestore.
Package operations: 1 install, 57 updates, 1 removal
• Removing pyparsing (3.0.9)
• Updating cachetools (5.2.0 -> 5.3.0)
• Updating protobuf (4.21.9 -> 4.21.12)
• Updating urllib3 (1.26.12 -> 1.26.14)
• …

Add pymysql package to support mysql protocol databases

---

noteable_magics/sql/meta_commands.py
tests/test_sql_magic_meta_commands.py

- \introspect doesn't properly handle unnamed primary keys (encountered today when testing Singlestore, a cloud hosted big data database that uses mysql client/server protocol). Will fail on some tables due to pydantic root validation proving that if there are pk columns being described, the pk must have a name.
- See https://noteableio.atlassian.net/browse/ENG-5416
- Fail to \introspect some tables.
- \introspection will succeed on tables / databases that support anonymous primary keys (ugh filthy things).
The safety error is fixed over in other branch, https://github.com/noteable-io/noteable-notebook-magics/pull/76, which will get merged before this branch.

Handle unnamed primary keys encountered within \introspect.

---

.github/workflows/main.yaml
poetry.lock
pyproject.toml

Use this alternate fork of JinjaSQL that has been made compat with modern jinja2. Nice person on interweb has already done the work bringing JinjaSQL up to speed with using 3.X series Jinja2 (sic). Alas the maintainer of Jinja2 official package has not done anything with the nice gift PR. Grr.
See their PR https://github.com/sripathikrishnan/jinjasql/pull/53 trying to get this into main JinjaSQL, but maintainer has fallen off of turnip truck.
When switching to this, we see happiness and upgraded jinja2 and markupsafe. Should then be compatible with that package the end user is trying to install that wants jinja2>3.0.
Package operations: 3 installs, 0 updates, 0 removals
• Installing markupsafe (2.1.2)
**• Installing jinja2 (3.1.2)**
• Installing jinjasql (0.1.9 f8c62d1)
The existing sql …

Use alternative JinjaSQL branch/build compatible with jinja2>=3.0.

---

poetry.lock
pyproject.toml

- Run "poetry update"
- Explicitly install pyarrow version 8.0 per demanded by snowflake 1.4.4.
Diffing 'pip freeze' output between main and this branch, the interesting upgrades are:
* pyarrow 6.0.1 -> 8.0.0
* SQLAlchemy 1.4.25 -> 1.4.46
and then also:
* ipykernel 6.20.2 -> 6.21.0
* ipython 8.8.0 -> 8.9.0
* jupyter_client 7.4.9 -> 8.0.2
* jupyter_core 5.1.5 -> 5.2.0
Comparing against what we end up getting inside of polymorph on integration right now (before this branch) [per this notebook](https://app.noteable-integration.us/f/2ee68f44-d989-4cf2-89dc-dfd09777d606/scratch.ipynb):
* IPython 8.9.0 (matching what this branch wants)
* ipykernel: 6.21.0 (matching what this branch wants)
* pyarrow: 6.0.1 (will be upgraded as expected …

Update dependency versions

---

.github/workflows/main.yaml
noteable_magics/sql/run.py
poetry.lock
pyproject.toml
tests/test_sql_magic.py
tox.ini

jinjasql 'named' format worked great for simple derefencing when feeding into SQLA text() elements, but the two conspire to fail with more complex jinja expressions like object attribute accesses such as `{{foo.id}}`.
Switch to drive jinjasql in 'numeric' mode instead to ensure that the resulting placeholders remain simple for text() to parse, at the expense of needing to post-process the bind params now coming as a list, needing to be converted to a dict of str keys -> value. 
- See the big new comment in run.py.
-  Jinja'd SQL cells like "select * from foo where id = {{slider.value}}" fail hard at SQLA level.
- Such expressions should work.

Fix jinjasql+sqla vs object attribute dereferencing notation at jinjasql level.

---

noteable_magics/datasource_postprocessing.py
noteable_magics/datasources.py
tests/test_datasources.py

- Kick in major side effect behavior of driving script `databricks-connect configure` in a brittle, bruteforce way when bootstrapping databricks, cluster_id is present in connect_args, and `databricks-connect` is found in $PATH.
- See ENG-5517.
- This is intended to be a late addition to release/canada.
- No special databricks post-processing.
- Will drive `databricks-connect configure` if we know our cluster-id.

ENG-5517 special behavior for databricks.

---

noteable_magics/datasource_postprocessing.py
tests/test_datasources.py

- @MSeal added some fixes, but not tests exercising the newly handled conditions in https://github.com/noteable-io/noteable-notebook-magics/pull/85 . This adds tests covering those added codepaths, plus then fixes for issues found from the tests:
- Must .decode() bytes coming up from Popen.stderr before adding to str when raising ValueError.
- Properly handle TimeoutException if databricks-connect takes too long.
- And then also prove that the right dict is popped from (@MSeal fixed that issue in prior PR, this adds a test proving it).
- Tighten the screws on the test over observing how databricks-connect was driven (tail bit of `test_extra_behavior()`):
- Prove script was fed _including newlines_ (original bug fixed in prior …

Test and fix the bugfixes.

---

noteable_magics/sql/meta_commands.py

- Fix introspecting databricks, at least for the three tables/views we have access to in our databricks account
- Unfortunately databricks SQLA dialect is telling us that the three relations are **both views and tables** (returned by inspector.get_table_names() AND ALSO ...get_view_names() .) Current logic in magics is to err on the side of view-ness in this case, but then the get_view_definiton() implementation of databricks driver is NotImplemented.
- But right now, FE doesn't do much anything different between an introspected table vs view except a different icon, so I'm not worried at this time.
- Introspection fails.
- Works. Local skaffold:
(Noel knows overly-long relation names need help here)

Eng 5808 fix introspect databricks

---

noteable_magics/datasources.py
poetry.lock
pyproject.toml
tests/test_datasources.py

- Prefer using 'psycopg2' over 'psycopg2-binary' driver. Will be updating polymorph in upcoming PR to apt-get install libpq-dev to get the latest postgres C client bindings installed, needed when installing psycopg2 from source.
- Similarly, switch away from using the (slow) python-only mysql driver pymysql to have newly created mysql or maraidb datasources (or edited preexisting ones) to the built-atop-mysql-client-C-library mysqlclient driver. The following polymorph PR will include explicitly apt-installing the mysql client library.
- Finally, similarly, switch new Singlestore datasources to use specific singlestore dialect+driver package sqlalchemy-singlestoredb. This is the bit that fixes our introspection issue.
- Using …

Eng 5806 cannot introspect the singlestore offers table

---

noteable/__init__.py
noteable/data_loader.py
noteable/sql/__init__.py
noteable/sql/connection.py
noteable/sql/magic.py
noteable/sql/run.py
tests/conftest.py
tests/test_data_loader.py
tests/test_sql_magic.py
tests/test_sql_magic_meta_commands.py

* Two new toplevel functions in package `noteable.sql`, aimed to let humans and AIs get at the SQLA objects backing SQL cells for fun and profit.
* `get_sqla_engine(name_or_handle: str) -> Optional[Engine]`
Given either the human-assigned name or the SQL cell handle for a datasource, return a SQLA Engine. Returns None if no such engine found.
* `get_sqla_connection(name_or_handle: str) -> Optional[sqlalchemy.engine.base.Connection]` . Given either the human-assigned name or the SQL cell handle for a datasource, return a SQLA connection. Returns None if no such connection found.
Implementations are in noteable.sql.connection module, imported into the parent package's __init__.
Then misc nonpublic cleanup:
* Move code around to be in better places, for example get stuff out of the data …

Refactor and make getting at SQL connections easy from python

---

noteable/ntbl.py

`tqdm.update` doesn't set the absolute progress, just increments, so we need to calculate the increment value.

Fix tqdm update value

---

noteable/datasource_postprocessing.py
tests/test_datasources.py

- Create data connection JSON form accepts two fields: verify server certificate and protocol.
- Broken when verify is set to True.
- Accept single new enum value `secure_connection` with options "Yes, use HTTPS", "Yes, use HTTPS and verify server certificate" and "No, use HTTP" and convert them accordingly to `verify` and `protocol` args for the driver.

Convert wordy verify enum to expected clickhouse driver args

---

noteable/datasource_postprocessing.py
tests/conftest.py
tests/test_datasources.py
tests/test_sql_magic.py

max_downoad_seconds needs to be popped out of connect_args regardless of if a database name was given or not.
Issue reported by user at https://community.noteable.io/c/issues-and-bugs/cant-connect-to-sqlite-database

Fix SQLite and memory driver vs. postprocess_sqlite popping

---

CHANGELOG.md
noteable/__init__.py
noteable/data_loader.py
noteable/datasources.py
noteable/sql/connection.py
noteable/sql/magic.py
noteable/sql/meta_commands.py
tests/conftest.py
tests/test_connection.py
tests/test_data_loader.py
tests/test_datasources.py
tests/test_sql_init_package.py
tests/test_sql_magic.py
tests/test_sql_magic_meta_commands.py

The inherited code from sql_magics had the Connection class playing double-duty as both the instances of connections as well as the registry of connections.
Separate these two roles in order to begin to pave the way for a class hierarchy of Connection types so that we can model the variations in our SQLAlchemy connection types more cleanly. This will let us more cleanly fix some existing bugs, model variations in warts in SQLA dialects, esp. at introspection time, better and more cleanly, as well as clear the road for implementing non-SQLA and even non-SQL text queryable connection types / integrations. Am initially eyeballing Jira / JQL as a MVP destination for this line of refactoring, but can see how getting much more of the …

Separate connection registry functionality from connection modeling.

---

CHANGELOG.md
noteable/datasources.py
noteable/sql/connection.py
tests/conftest.py
tests/test_datasources.py

- Fix bug where refactored bootstrap_datasource()  -> connection_registry.factory_and_register() was dropping create_engine_kwargs. Whoops.
- Datasources that needed to pass over create_engine_kwargs / connect_args would fail to be configured properly. That ... didn't include the PostgreSQL I manually clicktested with on Staging.
- No test case covered proving these facts make it down to the create_engine() call.
- They will work.
- New test proving that they make it over.

Fix bug where refactored bootstrap_datasource()

---

CHANGELOG.md
noteable/sql/sqlalchemy.py
tests/test_datasources.py
tests/test_sql_magic.py

- Force all SQLAlchemy datasource subtypes to be their own individual concrete classes individually declaring their own `needs_explicit_commit` value for sanity, correctness, and clarity.
- Stop expecting `sqlmagic_autocommit` being presented in gate-side metadata. Only consider the SQLAlchemy subtype's classlevel boolean. The field will be removed from Gate side in future work.
- Athena does _must not_  `quote_plus(connect_args['s3_staging_dir'])` -- they won't work encoded that way. It wants direct passing. Not sure where I got the idea that they had to be, but it doesn't work with 'em encoded this way, and the driver docs only say have to quote_plus username + password.
[This staging notebook](https://app.noteable-staging.us/f/5aa243f3-fcd7-4319-b907-c196badcc970/Test-Autocommit-Setting …

Fixes from clicktesting.

---

CHANGELOG.md
noteable/datasources.py
tests/test_datasources.py

- Don't mutate `metadata` passed to `bootstrap_datasource()`
- a `KeyError` would be raised, hiding the underlying error when creating a connection. In our case, `port` was an empty string when it should be `None`
- No `KeyError` is raised

Copy metadata dict to avoid mutating it

---

noteable/sql/sqlalchemy/__init__.py
noteable/sql/sqlalchemy/utils.py
tests/test_datasources.py

- Redshift dialect returns text() objects from get_view_definition(), surprising things and preventing encapsulation into pydantic message expecting exactly str. So capture and expliclty str() downgrade.
- Cannot introspect Redshift databases that have views.
- Introspection succeeds.

Fix Redshift vs view definitions

---

noteable/sql/sqlalchemy/__init__.py
poetry.lock
pyproject.toml
tests/test_datasources.py

- Create a new `SingleStoreDBConnection` class with preprocessing logic to add SingleStore connection attributes `program_name` and `program_version` corresponding to `noteable` and this package's version respectively.
- Replace `sqlalchemy-singlestoredb` installation with explicit `singlestoredb` installation and `sqlalchemy` as extras. 
Excerpt from an email from one of the SingleStore representatives:
>  We are requesting all SingleStore partners add a connection attribute to their connector to SingleStore, which will enable us to identify details about connections made to customers' SingleStore instances. It will help us track the health of the integration and joint customers. We will also be able to share these details …

Singlestore conn attrs
